# Generated by Django 4.0 on 2022-12-20 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_food'),
    ]

    operations = [
        migrations.CreateModel(
            name='Workout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('image_s', models.TextField(default='')),
                ('image_l', models.TextField(default='')),
                ('exercises', models.ManyToManyField(to='base.Exercise')),
            ],
        ),
    ]
