# Generated by Django 4.0 on 2023-01-02 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('base', '0009_meal'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.TextField(default='')),
                ('title', models.TextField(default='')),
                ('user', models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='auth.user')),
            ],
        ),
    ]
